<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>
    <Authors>CodeChops</Authors>
    <Company>CodeChops</Company>
    <Description>Open source edition of the CodeChops AI Video Coach Oqtane Module</Description>
    <Product>CodeChops.AIVideoCoach</Product>
    <Copyright>CodeChops</Copyright>
    <AssemblyName>CodeChops.Module.AIVideoCoach.Package.Oqtane</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\CodeChops.Module.AIVideoCoach.Client.csproj" />
    <ProjectReference Include="..\Server\CodeChops.Module.AIVideoCoach.Server.csproj" />
    <ProjectReference Include="..\Shared\CodeChops.Module.AIVideoCoach.Shared.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Condition="'$(OS)' == 'Windows_NT' And '$(Configuration)' == 'Debug'" Command="debug.cmd $(TargetFramework) $([System.String]::Copy('$(MSBuildProjectName)').Replace('.Package',''))"  />
	  <Exec Condition="'$(OS)' != 'Windows_NT' And '$(Configuration)' == 'Debug'" Command="bash $(ProjectDir)debug.sh $(TargetFramework) $([System.String]::Copy('$(MSBuildProjectName)').Replace('.Package',''))" />
	  <Exec Condition="'$(OS)' == 'Windows_NT' And '$(Configuration)' == 'Release'" Command="release.cmd $(TargetFramework) $([System.String]::Copy('$(MSBuildProjectName)').Replace('.Package',''))" />
	  <Exec Condition="'$(OS)' != 'Windows_NT' And '$(Configuration)' == 'Release'" Command="bash $(ProjectDir)release.sh $(TargetFramework) $([System.String]::Copy('$(MSBuildProjectName)').Replace('.Package',''))" />
  </Target>

</Project>
